# Generated by Django 2.2 on 2020-03-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
