# Generated by Django 2.2 on 2020-03-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0005_auto_20200323_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='company_name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
