# Generated by Django 2.2 on 2020-03-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0006_auto_20200325_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='required_documents',
            name='Name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
